server:
  port: 8080
  servlet:
    session:
      timeout: 15m
      cookie:
        max-age: 900

spring:
  application:
    name: discodeit
  boot:
    admin:
      client:
        url: http://localhost:9090
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
      enabled: true
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        highlight_sql: true
        default_batch_fetch_size: 1000
        generate_statistics: true;
        use_sql_comments: true;
    open-in-view: false
  session:
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session
  data:
    redis:
      host: localhost
      port: 6379
      password: qwerqwer

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org.hibernate.SQL: debug
    com.sprint.mission.discodeit: debug
    org.springframework.security: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true


discodeit:
  repository:
    type: file  # jcf or file
    file-directory: .discodeit
  storage:
    type: ${STORAGE_TYPE:local}
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:.discodeit/storage}
    s3:
      access-key: ${AWS_ACCESS_KEY_ID:}
      secret-key: ${AWS_SECRET_ACCESS_KEY:}
      region: ${AWS_REGION:}
      bucket: ${AWS_S3_BUCKET:}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600} # (기본값: 10분)

file:
  dir: .discodeit/storage

