spring:
  application:
    name: discodeit
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        highlight_sql: true
        default_batch_fetch_size: 1000
        generate_statistics: true;
        use_sql_comments: true;
    open-in-view: false
logging:
  level:
    com.sprint.mission.discodeit: info
    org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true


discodeit:
  storage:
    type: local
    local:
      root-path: ~/Desktop/1-sprint-mission

file:
  #dir: C:/Users/leeco/Desktop/codeit_sprint/mission/1-sprint-mission/data_storage/
  dir: ${user.home}/app_uploads/
